[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ITensorFormatter = "b6bf39f1-c9d3-4bad-aad8-593d802f65fd"
ITensorNetworksNext = "302f2e75-49f0-4526-aef7-d8ba550cb06c"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"

[sources.ITensorNetworksNext]
path = ".."

[compat]
Documenter = "1"
ITensorFormatter = "0.2.27"
ITensorNetworksNext = "0.11"
Literate = "2"
